#include "parserDef.h"
//~ void createParseTable(grammar G, int T, Set ffset)
//~ {
	//~ 
//~ }
int main()
{
	printf("here");
	grammar G;
	FILE* fp =fopen("Grammar","r");
	int i,j;
	
	printf("grammar is %s\n",G[87][5]);
	Set ffset={{"MAIN","\0"},
					{"INT","REAL","STRING","MATRIX","SQO","READ","PRINT","ID","FUNID","IF","FUNCTION","\0"},
					{"END","\0"},
					{"INT","REAL","STRING","MATRIX","SQO","READ","PRINT","ID","FUNID","IF","FUNCTION","\0"},
					{"INT","REAL","STRING","MATRIX","SQO","READ","PRINT","ID","FUNID","IF","\0"},
					{"FUNCTION","\0"},
					{"INT","REAL","STRING","MATRIX","\0"},
					{"ID","\0"},
					{"SQO","\0"},
					{"IF","\0"},
					{"READ","PRINT","\0"},
					{"FUNID","\0"},
					{"FUNCTION","\0"},
					{"INT","REAL","STRING","MATRIX","\0"},
					{"INT","\0"},
					{"REAL","\0"},
					{"STRING","\0"},
					{"MATRIX","\0"},
					{"COMMA","\0"},
					{"SQC","\0"},
					{"INT","REAL","STRING","MATRIX","\0"},
					{"ID","\0"},
					{"COMMA","\0"},
					{"SQC","SEMICOLON","\0"},
					{"ID","\0"},
					{"SQO","\0"},
					{"ID","\0"},
					{"SQC	SQO","\0"},
					{"OP","ID","NUM","RNUM","STR","SQO","\0"},
					{"SIZE","\0"},
					{"FUNID","\0"},
					{"SIZE","\0"},
					{"FUNID","\0"},
					{"SIZE","\0"},
					{"IF","\0"},
					{"ELSE","\0"},
					{"ENDIF","\0"},
					{"INT","REAL","STRING","MATRIX","SQO","READ","PRINT","ID","FUNID","IF","\0"},
					{"ENDIF","ELSE","\0"},
					{"READ","\0"},
					{"PRINT","\0"},
					{"FUNID","\0"},
					{"ID","NUM","RNUM","STR","SQO","\0"},
					{"CL","\0"},
					{"COMMA","\0"},
					{"CL","\0"},
					{"OP","ID","NUM","RNUM","STR","SQO","\0"},
					{"CL","SEMICOLON","\0"},
					{"PLUS","MINUS","\0"},
					{"OP","ID","NUM","RNUM","STR","SQO","\0"},
					{"PLUS","MINUS","CL","SEMICOLON","\0"},
					{"MUL","DIV","\0"},
					{"CL	OP","\0"},
					{"ID","NUM","RNUM","STR","SQO","\0"},
					{"PLUS","\0"},
					{"MINUS","\0"},
					{"MUL","\0"},
					{"DIV","\0"},
					{"OP","\0"},
					{"ID","NUM","RNUM","\0"},
					{"ID","\0"},
					{"NUM","\0"},
					{"RNUM","\0"},
					{"ID","\0"},
					{"NUM","\0"},
					{"RNUM","\0"},
					{"ID","\0"},
					{"STR","\0"},
					{"SQO","\0"},
					{"SQO","\0"},
					{"NUM","\0"},
					{"SQC","\0"},
					{"SEMICOLON","\0"},
					{"NUM","\0"},
					{"SEMICOLON","SQC","\0"},
					{"COMMA","\0"},
					{"COMMA","\0"},
					{"SEMICOLON","SQC","\0"},
					{"ID","\0"},
					{"AND","\0"},
					{"OR","\0"},
					{"LT","\0"},
					{"LE","\0"},
					{"EQ","\0"},
					{"GT","\0"},
					{"GE","\0"},
					{"NE","\0"},
					{"NOT","\0"}
	};
	printf("ffset is %s",ffset[87][0]);
	//~ createParseTable(G,2,ffset);
	return 0;
}
